### ISSUE TITLE
Failsafe for disconnecting from a room

### ISSUE THREAD

**Issue by stueynet** [blackuy/react-native-twilio-video-webrtc#56] opened 2017-10-03 13:28 UTC
Does anyone employ a way to ensure a user correctly disconnects from a room. We are finding there are situations where .disconnect() does not actually disconnect them. We use sockets to notify a user when a video chat is over. We listen for that and ha sleep disconnecting on the client side but it’s not consistent. Is calling that one method sufficient?

Would really appreciate some example code on this.

**Comment by bilby91** [comment] 2017-11-23 21:08
Duplicate of #63 , will add a note on the README

**Closed by bilby91** 2017-11-23 21:08 UTC
