### ISSUE TITLE
Android - Could not find org.webrtc:google-webrtc:1.0.30039

### ISSUE THREAD

**Issue by railsfactory-gaurav** [blackuy/react-native-twilio-video-webrtc#553] opened 2021-09-24 03:45 UTC
I am getting this error while running yarn android. 
It's working on iOS.

```
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.webrtc:google-webrtc:1.0.30039.
```

### Steps to reproduce
1.  Run yarn android after adding react-native-twilio-video-webrtc

### Expected behavior
The project must build

### Actual behavior
Build error

### Environment
- **Node.js version**: 16.9.1
- **React Native version**: 0.65.1
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment] 2021-09-24 04:08
Dupe of #543

**Closed by slycoder** 2021-09-24 04:08 UTC

**Comment by nitishkumar325** [comment] 2022-06-16 11:54
still facing this issue

**Comment by bennaaym** [comment] 2022-08-05 18:18
@nitishkumar325 Did you find a solution for this issue because I'm facing the same issue [#627](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/627#issuecomment-1206721377)?

**Comment by logan0900** [comment] 2022-09-16 22:11
@railsfactory-gaurav  @nitishkumar325  @bennaaym  Guys i'm facing the same issue. so if you resolve the problem then please update me. :) 
![Capturea](https://user-images.githubusercontent.com/58814997/190812710-e17b4e63-3c44-4891-a132-78fb24b000b0.PNG)

**Comment by logan0900** [comment] 2022-09-16 23:34
Problem solved by adding   jcenter()   in build.gradlew. cheers (Y)

**Comment by ALEXGREENCH** [comment] 2023-06-26 16:22
```
    allprojects {
        repositories {
            ..
            maven { url "https://raw.githubusercontent.com/alexgreench/google-webrtc/master" }
        }
    }
```
