### ISSUE TITLE
Compile Java for :react-native-twilio-video-webrtc:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by lisa-nguyen-goldenowl** [blackuy/react-native-twilio-video-webrtc#221] opened 2019-08-16 03:46 UTC
### Steps to reproduce
Setup project for android:
1. Install package using yarn: 
`yarn add https://github.com/blackuy/react-native-twilio-video-webrtc`

2. Add the library to settings.gradle:  
`include ':react-native-twilio-video-webrtc'`
`project(':react-native-twilio-video-webrtc').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-twilio-video-webrtc/android')`

<img width="1184" alt="demoTwilioRN____repos_private_demoTwilioRN_android__-_____settings_gradle__demoTwilioRN_" src="https://user-images.githubusercontent.com/52815733/63141785-33f23880-c011-11e9-8d2e-3302e16f9689.png">

3. Include the library in dependencies in android/app/build.gradle:

`dependencies {`
`    .....`
`    .....`
`    .....`
`    implementation project(path: ':react-native-twilio-video-webrtc')`
`}`

<img width="1330" alt="demoTwilioRN____repos_private_demoTwilioRN_android__-_app" src="https://user-images.githubusercontent.com/52815733/63141913-b0851700-c011-11e9-8d59-9481add7ca3e.png">

4. Load the package in MainApplication.java:

`import com.twiliorn.library.TwilioPackage;`

<img width="640" alt="demoTwilioRN____repos_private_demoTwilioRN_android__-_____app_src_main_java_com_demotwiliorn_MainApplication_java__app_-3" src="https://user-images.githubusercontent.com/52815733/63142049-6486a200-c012-11e9-8d88-fd2502fd89ed.png">

5. Update the getPackages() method  in MainApplication.java:

`    protected List<ReactPackage> getPackages() {`
`        return Arrays.<ReactPackage>asList(`
`            ...`
`            new TwilioPackage()`
`        );`
`    }`

<img width="674" alt="demoTwilioRN____repos_private_demoTwilioRN_android__-_____app_src_main_java_com_demotwiliorn_MainApplication_java__app_-4" src="https://user-images.githubusercontent.com/52815733/63142069-7ff1ad00-c012-11e9-860f-1e39f746cfc9.png">

6. Add camera and audio permissions to your AndroidManifest.xml file:

`    <uses-permission android:name="android.permission.CAMERA" />`
`    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />`
`    <uses-permission android:name="android.permission.RECORD_AUDIO" />`
`    <uses-feature android:name="android.hardware.camera" android:required="false" />`
`    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />`
`    <uses-feature android:name="android.hardware.microphone" android:required="false" />`

7. (Additional) Add these two lines to proguard-rules.pro:

`  -keep class org.webrtc.** { *; }`
`  -keep class com.twilio.** { *; }`

### Expected behaviour
Build android project successfully

### Actual behaviour
Compile fail 
<img width="1380" alt="demoTwilioRN____repos_private_demoTwilioRN_android__-_____app_src_main_AndroidManifest_xml__app_" src="https://user-images.githubusercontent.com/52815733/63141545-4ddf4b80-c010-11e9-9a47-187ecb8819d8.png">

### Environment
- **Node.js version**: 12.8.0
- **React Native version**: 0.60.5
- **React Native platform + platform version**: iOS 12.4, Android 9.0 API 28

### react-native-twilio-video-webrtc
**Version**: 1.0.2

**Comment by slycoder** [comment] 2019-08-16 05:03
Do you have some details on what the compilation errors are (i.e. can you expand the errors under "Java compiler" in the screenshot)?

Also make sure you're installing from master.

**Comment by tbiinfotech** [comment] 2019-09-05 08:25
I am facing the same issue i am using react-native version 0.60.5 and follow all the steps to link the library which are also mentioned above but get the error. 

I have installed the package from master but get the same error.

![Screenshot_2](https://user-images.githubusercontent.com/17080270/64324860-beacce80-cfe4-11e9-873f-a487131f5d67.png)

**Comment by slycoder** [comment] 2019-09-05 18:10
Do you have the compiler output with more details on the error?

**Comment by tbiinfotech** [comment] 2019-09-06 09:36
Here is the compiler output. Please check and let me know if you need anything else. Thanks

![image](https://user-images.githubusercontent.com/17080270/64417963-bb364780-d0b7-11e9-91c6-79455d31cb50.png)

**Comment by slycoder** [comment] 2019-09-06 16:16
@tbiinfotech I think master should be fixed now.

**Comment by tbiinfotech** [comment] 2019-09-09 09:09
Ok great thanks for your help the issue is fixed now.

**Comment by tbiinfotech** [comment] 2019-09-19 11:56
I am facing same issue with the react native version 0.59.9 its fixed with 0.60.5 but not with the 0.59.9 version can you please check.

**Comment by slycoder** [comment] 2019-09-20 20:33
You're getting the same stack trace?  Can you double check that you've pulled the latest master?

**Comment by evalenzuela** [comment] 2020-12-17 12:45
I am getting a similar error, can you help please?

```
> Task :react-native-twilio-video-webrtc:compileDebugJavaWithJavac FAILED
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:25: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:26: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:112: error: cannot find symbol
    @StringDef({Events.ON_CAMERA_SWITCHED,
     ^
  symbol:   class StringDef
  location: class CustomTwilioVideoView
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoViewManager.java:11: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\RNVideoViewGroup.java:13: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\RNVideoViewGroup.java:39: error: cannot find symbol
    @StringDef({ON_FRAME_DIMENSIONS_CHANGED})
     ^
  symbol:   class StringDef
  location: class RNVideoViewGroup
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioRemotePreviewManager.java:10: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioVideoPreviewManager.java:10: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoViewManager.java:73: error: cannot find symbol
    public void receiveCommand(CustomTwilioVideoView view, int commandId, @Nullable ReadableArray args) {
                                                                           ^
  symbol:   class Nullable
  location: class CustomTwilioVideoViewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoViewManager.java:132: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class CustomTwilioVideoViewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoViewManager.java:171: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class CustomTwilioVideoViewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioRemotePreviewManager.java:35: error: cannot find symbol
    public void setScaleType(TwilioRemotePreview view, @Nullable String scaleType) {
                                                        ^
  symbol:   class Nullable
  location: class TwilioRemotePreviewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioRemotePreviewManager.java:45: error: cannot find symbol
    public void setTrackId(TwilioRemotePreview view, @Nullable String trackSid) {
                                                      ^
  symbol:   class Nullable
  location: class TwilioRemotePreviewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioVideoPreviewManager.java:34: error: cannot find symbol
    public void setScaleType(TwilioVideoPreview view, @Nullable String scaleType) {
                                                       ^
  symbol:   class Nullable
  location: class TwilioVideoPreviewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\TwilioVideoPreviewManager.java:43: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class TwilioVideoPreviewManager
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:781: error: cannot find symbol
            public void onReconnecting(@NonNull Room room, @NonNull TwilioException twilioException) {
                                        ^
  symbol: class NonNull
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:781: error: cannot find symbol
            public void onReconnecting(@NonNull Room room, @NonNull TwilioException twilioException) {
                                                            ^
  symbol: class NonNull
D:\Project\node_modules\react-native-twilio-video-webrtc\android\src\main\java\com\twiliorn\library\CustomTwilioVideoView.java:786: error: cannot find symbol
            public void onReconnected(@NonNull Room room) {
                                       ^
  symbol: class NonNull
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
18 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-twilio-video-webrtc:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
83 actionable tasks: 2 executed, 81 up-to-date
```

**Comment by slycoder** [comment] 2020-12-18 01:46
@evalenzuela  This appears to be a different compilation error.  This is due to you using androidX; you can either run jettify or pull from the release/v2.0 branch.

**Closed by slycoder** 2020-12-18 01:46 UTC

**Comment by YOEL311** [comment] 2021-06-20 08:04
Can't use Android X without version 2?

**Comment by owenadley** [comment] 2021-07-13 13:50
@YOEL311 you can use latest, just ensure you run 'npx jetify' are installing.

**Comment by TomasSestak** [comment] 2021-11-26 10:25
> @YOEL311 you can use latest, just ensure you run 'npx jetify' after installing.

I have the latest release and also tried:

**npx jetify** with this result:
Jetifier is deprecated. Future versions of react-native CLI may not run it by default.
Jetifier found 2098 file(s) to forward-jetify. Using 8 workers...
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java
Jetifier: propose an AndroidX conversion PR to this repository: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java

But still getting this error, i'm building it with eas-build i bare workflow.

**Comment by TomasSestak** [comment] 2021-11-26 11:57
I solved it by adding 
"eas-build-post-install": "jetify" to scripts in package.json and also adding jetify as devDependency

**Comment by neetable-abhilash** [comment] 2023-05-12 05:45
npx jetify worked for me

**Comment by zain-khalid** [comment] 2024-07-15 20:06
npx jetify worked for me
