### ISSUE TITLE
Issue In android 

### ISSUE THREAD

**Issue by surendrasourcesoft** [blackuy/react-native-twilio-video-webrtc#301] opened 2020-05-13 13:49 UTC
### Steps to reproduce
1.Craete a new project
2.add this library as per instruction android Gradle-wrapper is given below
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

3.Run the app in android and you will see app is crashed

No static method create()Ltvi/webrtc/EglBase; in class Ltvi/webrtc/EglBase; or its super classes (declaration of 'tvi.webrtc.EglBase' appears in /data/app/com.clearcarehealth.docme--9XSXmjYifMbs2yJbxGoWw==/base.apk)

**Comment by slycoder** [comment] 2020-05-13 16:52
Dupe of #278

**Closed by slycoder** 2020-05-13 16:52 UTC
